### Create a new ledger
POST http://localhost:3000/api/ledgers
Content-Type: application/json

{
  "name": "September Ledger"
}


### Create a new guest
POST http://localhost:3000/api/guests
Content-Type: application/json

{
  "name": "Jobs Zhao",
  "phone": "2133086336",
  "email": "jobszhao99@gmail.com"
}

### Create a new Booking
curl -X POST http://localhost:3000/api/bookings \
  -H "Content-Type: application/json" \
  -d '{
    "roomId": "cmf6355vu00678nwqdk4lixz9",
    "guestId": "cmf4hhyej000a8naxwtfl43is",
    "checkIn": "2025-03-05",
    "checkOut": "2025-03-23",
    "channel": "AIRBNB",
    "guestTotalCents": 87740,
    "payoutCents": 78571,
    "confirmationCode": "HM3QDH8SHY",
    "status": "NEW"
  }'